### ISSUE TITLE
couldn't run

### ISSUE THREAD

**Issue by lex93ushakov** [StochasticEngineer/Splines#1]
```sh
yser@host:/tmp/Splines$ python3 CurveFitter.py
Traceback (most recent call last):
  File "CurveFitter.py", line 484, in <module>
    main()
  File "CurveFitter.py", line 465, in main
    c.approximate_with_optimal_grid(s, points, q, 1e-3, 1e-3)
  File "CurveFitter.py", line 341, in approximate_with_optimal_grid
    if not self.spec_dimensional_minimization(spline, points, smooth_weight, direction, error_derivative, fixed_knots):
  File "CurveFitter.py", line 159, in spec_dimensional_minimization
    alpha_max = math.inf
AttributeError: 'module' object has no attribute 'inf'
```

Can you help to fix it?

**Comment by astralord** [comment]
The reason is most likely to be that you use Python2. Try to change math.inf into float('inf').

**Comment by lex93ushakov** [comment]
I had use `python3`. And, thank you, your fix helps.
